import type { Metadata } from 'next';
import { Baloo_2 } from 'next/font/google';

import { MainWrapper } from '@/common/components/components';

const baloo = Baloo_2({
  variable: '--font-baloo',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'My Lemon Life Portfolio',
  description: 'Generated by mylemonlife',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <link rel="icon" href="/miku_green.png" type="image/png" />
      <MainWrapper>
        <body className={`${baloo.variable}`}>{children}</body>
      </MainWrapper>
    </html>
  );
}
