import type { Metadata } from 'next';
import { Baloo_2 } from 'next/font/google';
import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { notFound } from 'next/navigation';

import { routing } from '@/i18n/routing';
import { MainWrapper } from '@/common/components/components';

const baloo = Baloo_2({
  variable: '--font-baloo',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'My Lemon Life Portfolio',
  description: 'Generated by mylemonlife',
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale}>
      <link rel="icon" href="/miku_green.png" type="image/png" />
      <MainWrapper>
        <body className={`${baloo.variable}`}>
          <NextIntlClientProvider>{children}</NextIntlClientProvider>
        </body>
      </MainWrapper>
    </html>
  );
}
